/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package usuarios.vista;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import usuarios.controlador.daoUsuario.ContratoControlDao;
import usuarios.controlador.daoUsuario.ImparteControl1;
import usuarios.controlador.daoUsuario.PeriodoContratoControlDao1;
import usuarios.modelo.Docente;
import usuarios.vista.UtilVista.UtilVistaDocente;
import vista.modelo.ModeloTablaContrato;

/**
 *
 * @author Alejandro
 */
public class ContratoDocente extends javax.swing.JFrame {
    private ContratoControlDao controlContrato=new ContratoControlDao();
    private ImparteControl1 controlImparte=new ImparteControl1();
    private PeriodoContratoControlDao1 controlPeriodo=new PeriodoContratoControlDao1();
    private Docente docente;
    private ModeloTablaContrato mtc=new ModeloTablaContrato();
    /**
     * Creates new form ContratoDocente
     */
    public ContratoDocente() {
        initComponents();
        this.setLocationRelativeTo(null);
        Limpiar();
        pnlAzul.setIcon(new ImageIcon("fotos/Azul.png"));
        pnlGris.setIcon(new ImageIcon("fotos/Celeste.jpg"));
    }
    public ContratoDocente(Docente usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        pnlAzul.setIcon(new ImageIcon("fotos/Azul.png"));
        pnlGris.setIcon(new ImageIcon("fotos/Celeste.jpg"));
        Limpiar();
        this.docente = usuario;
    }
    private void Limpiar() {
        try {
            UtilVistaDocente.CargarDocentes(cbxDocente);
        } catch (Exception e) {
        }
        tblMostrar.clearSelection();
        jcFinal.getDate();
        jcInicio.getDate();
        cbxDocente.setSelectedIndex(-1);
        CargarTabla();
        controlContrato.setContrato(null);
        controlImparte.setImparte(null);
        controlPeriodo.setPeriodo(null);

    }

    private void CargarTabla() {
        mtc.setContrato(controlImparte.getImparte());
        tblMostrar.setModel((TableModel) mtc);
        tblMostrar.updateUI();
    }
    private Boolean Validar() {
        return (!txtSalario.getText().trim().isEmpty());
    }
    private void Guardar() {
        
        if (Validar()) {          
            controlImparte.getImparte1().setId_Docente(UtilVistaDocente.ObtenerDocente(cbxDocente));
            //controlContrato.getContrato1().setSalario(Double.parseDouble(txtSalario.getText()));
            controlPeriodo.getPeriodo1().setFechaInicio(jcInicio.getDate());
            if (controlImparte.persist()) {
                JOptionPane.showMessageDialog(null, "Datos guardados con exito");
                controlPeriodo.setPeriodo1(null);
                CargarTabla();
                Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo guardar");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Falta llenar campos  ");

        }
    }
    private void cargarVista() {
        int fila = tblMostrar.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Escoja un registtro de la tabla");
        } else {
            try {
                String contrato=String.valueOf(controlContrato.getContrato1().getSalario());
               controlImparte.setImparte1(mtc.getContrato().getInfo(fila));
                jcInicio.setDate(controlImparte.getImparte1().getId_Contrato().getId_periodo().getFechaInicio());
                jcFinal.setDate(controlImparte.getImparte1().getId_Contrato().getId_periodo().getFechaFinal());
                txtSalario.setText(contrato);
                
                cbxDocente.setSelectedItem(controlImparte.getImparte1().getId_Docente().getNombre());
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }

        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAzul = new org.edisoncor.gui.panel.PanelImage();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        cbxDocente = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jcFinal = new com.toedter.calendar.JDateChooser();
        jcInicio = new com.toedter.calendar.JDateChooser();
        pnlGris = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrar = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAzul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("        CONTRATOS");
        pnlAzul.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 290, 90));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha Final:");
        pnlAzul.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 150, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Docente:");
        pnlAzul.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Salario:");
        pnlAzul.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha de Inicio:");
        pnlAzul.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 150, -1));
        pnlAzul.add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 290, -1));

        pnlAzul.add(cbxDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 290, -1));

        btnEliminar.setText("ELIMINAR DATOS");
        pnlAzul.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, -1, -1));

        btnGuardar.setText("GUARDAR DATOS");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlAzul.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        btnModificar.setText("MODIFCAR DATOS");
        pnlAzul.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        jButton4.setText("GUARDAR DATOS");
        pnlAzul.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));
        pnlAzul.add(jcFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 280, -1));
        pnlAzul.add(jcInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 280, -1));

        getContentPane().add(pnlAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 617));

        pnlGris.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("     REGISTRO DE CONTRATOS");
        pnlGris.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 420, 90));

        tblMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMostrarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMostrar);

        pnlGris.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 260));

        getContentPane().add(pnlGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 0, 560, 617));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMostrarMouseClicked
  
    }//GEN-LAST:event_tblMostrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContratoDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContratoDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContratoDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContratoDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContratoDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<Object> cbxDocente;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jcFinal;
    private com.toedter.calendar.JDateChooser jcInicio;
    private org.edisoncor.gui.panel.PanelImage pnlAzul;
    private org.edisoncor.gui.panel.PanelImage pnlGris;
    private javax.swing.JTable tblMostrar;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
