/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tareas.vista;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import tareas.controlador.controladorTarea.detalleTarea;
import tareas.controlador.controladorTarea.envioTarea;
import tareas.vista.modeloTabla.modeloTareaEstudiante;
    
 /*
 * @author ALEJANDRO
 */
public class EntregaTarea extends javax.swing.JFrame {
    private detalleTarea detalleTarea=new detalleTarea();
    private envioTarea controlEnvio=new envioTarea();
    modeloTareaEstudiante mte=new modeloTareaEstudiante();

    
    /**
     * Creates new form TareaEstudiante
     */
   public EntregaTarea() {
        initComponents();
        this.setLocationRelativeTo(null);
        Limpiar();
    }
    public void recibirDatosTarea(String tituloTarea, String descripcion){
        controlEnvio.getTareaEstudiante1().setTituloTarea(tituloTarea);
        txtTitulo.setText(controlEnvio.getTareaEstudiante1().getTituloTarea());
        controlEnvio.getTareaEstudiante1().setDescripcion(descripcion);
        txtDescripcion.setText(controlEnvio.getTareaEstudiante1().getDescripcion());
         
        
    }
    
    private void CargarTabla() {
        mte.setTarea(controlEnvio.getTareaEstudiante());
        tblMostrarDatos.setModel((TableModel) mte);
        tblMostrarDatos.updateUI();
    }
     private void Limpiar() {
         txtNombreTarea.setText(" ");
         txtLink.setText(" ");
        tblMostrarDatos.clearSelection();
        CargarTabla();
        controlEnvio.setTareaEstudiante1(null);
    }
     private Boolean Validar() {
        return (!txtTitulo.getText().trim().isEmpty()
                && !txtLink.getText().trim().isEmpty());
    }
    private void GuardarTarea(){
        detalleTarea.getTareaEstudiante1().setNombreArchivo(txtNombreTarea.getText());
        detalleTarea.getTareaEstudiante1().setLink(txtLink.getText());
        if (detalleTarea.persist()) {
                JOptionPane.showMessageDialog(null, "Datos guardados con exito");
                detalleTarea.setTareaEstudiante1(null);
                Limpiar();
                publicar();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo guardar");
            }
    }
    private void Guardar() {
        
        if (Validar()) {          
            recibirDatosTarea(txtTitulo.getText(), txtLink.getText());
            if (controlEnvio.persist()) {
                JOptionPane.showMessageDialog(null, "Datos guardados con exito");
                controlEnvio.setTareaEstudiante1(null);
                CargarTabla();
                Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo guardar");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Falta llenar campos  ");

        }
    }
    private void cargarVista() {
        int fila = tblMostrarDatos.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Escoja un registtro de la tabla");
        } else {
            try {
                controlEnvio.setTareaEstudiante1(mte.getTarea().getInfo(fila));
                txtTitulo.setText(controlEnvio.getTareaEstudiante1().getTituloTarea());
                txtDescripcion.setText(controlEnvio.getTareaEstudiante1().getDescripcion());
                
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }

        }
    }
    private void publicar() {
        EntregaTarea ea=new EntregaTarea();
        ea.recibirDatosTarea(txtNombreTarea.getText(), txtLink.getText());
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtMateria = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtLink = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrarDatos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNombreTarea = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(204, 0, 0));
        btnRegresar.setText("REGRESAR AL MENÚ");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 220, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 535));

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENTREGA DE TAREAS");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Materia:");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Descripción:");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txtTitulo.setBackground(new java.awt.Color(255, 255, 204));
        txtTitulo.setEnabled(false);
        panel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 400, -1));

        txtMateria.setBackground(new java.awt.Color(255, 255, 204));
        txtMateria.setEnabled(false);
        txtMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMateriaActionPerformed(evt);
            }
        });
        panel1.add(txtMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 400, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Título  Tarea:");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txtLink.setBackground(new java.awt.Color(255, 255, 204));
        panel1.add(txtLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 360, -1));

        tblMostrarDatos.setBackground(new java.awt.Color(255, 255, 255));
        tblMostrarDatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblMostrarDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMostrarDatos);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 520, 110));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Link de tarea:");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        txtDescripcion.setBackground(new java.awt.Color(255, 255, 204));
        txtDescripcion.setEnabled(false);
        panel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 400, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre Archivo:");
        panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        txtNombreTarea.setBackground(new java.awt.Color(255, 255, 204));
        panel1.add(txtNombreTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 370, -1));

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 150, -1));

        btnSeleccionar.setText("SELECCIONAR");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        panel1.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 150, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 610, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMateriaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      GuardarTarea();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        cargarVista();
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MenuGestion mg=new MenuGestion(this, rootPaneCheckingEnabled);
        this.dispose();
        mg.setVisible(true);
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntregaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntregaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntregaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntregaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntregaTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.panel.Panel panel1;
    private javax.swing.JTable tblMostrarDatos;
    public static javax.swing.JTextField txtDescripcion;
    public static javax.swing.JTextField txtLink;
    public static javax.swing.JTextField txtMateria;
    public static javax.swing.JTextField txtNombreTarea;
    public static javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

}
