/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tareas.vista;

import exeption.EmptyException;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import matricula.vista.EstudianteMatricula;
import matricula.vista.GuardarCiclo;
import tareas.controlador.controladorTarea.administrarTarea1;
import tareas.controlador.controladorTarea.detalleTarea;
import tareas.controlador.controladorTarea.envioTarea;
import tareas.controlador.controladorTarea.reporteTarea1;
import tareas.vista.modeloTabla.modeloReporteCalificacion;
import tareas.vista.modeloTabla.modeloTareaEstudiante;
import usuarios.modelo.Estudiante;
import usuarios.vista.LoginPrincipal;
import usuarios.vista.Menu;
    
 /*
 * @author ALEJANDRO
 */
public class ReporteNotas extends javax.swing.JFrame {
    private detalleTarea detalleTarea=new detalleTarea();
    private envioTarea controlEnvio=new envioTarea();
    private modeloReporteCalificacion mpc=new modeloReporteCalificacion();
    private reporteTarea1 controlReporte=new reporteTarea1();
    modeloTareaEstudiante mte=new modeloTareaEstudiante();
    private Estudiante estudiante;
    /**
     * Creates new form TareaEstudiante
     */
   public ReporteNotas() {
        initComponents();
        this.setLocationRelativeTo(null);
        Limpiar();
        Limpiar1();
                pnlAzul.setIcon(new ImageIcon("fotos/Azul.png"));
        pnlGris.setIcon(new ImageIcon("fotos/Celeste.jpg"));
    }

    public ReporteNotas(Estudiante estudiante) throws HeadlessException {
        this.estudiante = estudiante;
        initComponents();
        this.setLocationRelativeTo(null);
        Limpiar();
        Limpiar1();
        this.estudiante = estudiante;
        pnlAzul.setIcon(new ImageIcon("fotos/Azul.png"));
        pnlGris.setIcon(new ImageIcon("fotos/Celeste.jpg"));
    }
   
   
    public void recibirDatosReporte(String tituloTarea, String descripcion){
        controlEnvio.getTareaEstudiante1().setTituloTarea(tituloTarea);
        txtTitulo.setText(controlEnvio.getTareaEstudiante1().getTituloTarea());
        controlEnvio.getTareaEstudiante1().setDescripcion(descripcion);
        txtDescripcion.setText(controlEnvio.getTareaEstudiante1().getDescripcion());
 
    }
    public void recibirDatos1(String nota,String retroaliemtnacion){
        controlReporte.getTareaEstudiante1().setNota(Float.parseFloat(nota));
        String Nota=String.valueOf(controlReporte.getTareaEstudiante1().getNota());
        txtNota.setText(Nota);
        controlReporte.getTareaEstudiante1().setRetroalimentacion(retroaliemtnacion);
        txtRetroaliemntacion.setText(controlReporte.getTareaEstudiante1().getRetroalimentacion());
    }
    
    private void CargarTabla() {
        mpc.setReporte(controlReporte.getTareaEstudiante());
        tblMostrarDatos.setModel((TableModel) mpc);
        tblMostrarDatos.updateUI();
    }
    private void CargarTabla1() {
        mte.setTarea(controlEnvio.getTareaEstudiante());
        tblMostrarDatos1.setModel((TableModel) mte);
        tblMostrarDatos1.updateUI();
    }
     private void Limpiar() {
        tblMostrarDatos.clearSelection();
        CargarTabla();
        controlReporte.setTareaEstudiante1(null);
    }
      private void Limpiar1() {
        tblMostrarDatos1.clearSelection();
        CargarTabla1();
        controlEnvio.setTareaEstudiante1(null);
    }
     private Boolean Validar() {
        return (!txtTitulo.getText().trim().isEmpty()
                && !txtRetroaliemntacion.getText().trim().isEmpty());
    }
    private void Guardar() {
        
        if (Validar()) {          
            recibirDatosReporte(txtTitulo.getText(), txtDescripcion.getText());
            recibirDatos1(txtNota.getText(), txtRetroaliemntacion.getText());
            if (controlEnvio.persist()) {
                JOptionPane.showMessageDialog(null, "Datos guardados con exito");
                controlEnvio.setTareaEstudiante1(null);
                CargarTabla();
                Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo guardar");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Falta llenar campos  ");

        }
    }
    

   
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAzul = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMateria = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        txtRetroaliemntacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pnlGris = new org.edisoncor.gui.panel.PanelImage();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMostrarDatos1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrarDatos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        btnIncio1 = new javax.swing.JMenuItem();
        btnMatricula1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        btnSalir1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAzul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REPORTE DE NOTAS");
        pnlAzul.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Materia:");
        pnlAzul.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtMateria.setBackground(new java.awt.Color(255, 255, 204));
        txtMateria.setEnabled(false);
        txtMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMateriaActionPerformed(evt);
            }
        });
        pnlAzul.add(txtMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 290, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Título  Tarea:");
        pnlAzul.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtTitulo.setBackground(new java.awt.Color(255, 255, 204));
        txtTitulo.setEnabled(false);
        pnlAzul.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 290, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Descripción:");
        pnlAzul.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtDescripcion.setBackground(new java.awt.Color(255, 255, 204));
        txtDescripcion.setEnabled(false);
        pnlAzul.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 300, 40));

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nota:");
        pnlAzul.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        txtNota.setBackground(new java.awt.Color(255, 255, 204));
        txtNota.setEnabled(false);
        pnlAzul.add(txtNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 300, -1));

        txtRetroaliemntacion.setBackground(new java.awt.Color(255, 255, 204));
        txtRetroaliemntacion.setEnabled(false);
        pnlAzul.add(txtRetroaliemntacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 300, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Retroalimentación:");
        pnlAzul.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        getContentPane().add(pnlAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 550));

        pnlGris.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMostrarDatos1.setBackground(new java.awt.Color(255, 255, 255));
        tblMostrarDatos1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblMostrarDatos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane3.setViewportView(tblMostrarDatos1);

        pnlGris.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 370, 200));

        tblMostrarDatos.setBackground(new java.awt.Color(255, 255, 255));
        tblMostrarDatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblMostrarDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tblMostrarDatos);

        pnlGris.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 370, 230));

        getContentPane().add(pnlGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 440, 550));

        jMenu3.setText("Menu");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnIncio1.setText("Inicio");
        btnIncio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncio1ActionPerformed(evt);
            }
        });
        jMenu3.add(btnIncio1);

        btnMatricula1.setText("Matriculas");
        btnMatricula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricula1ActionPerformed(evt);
            }
        });
        jMenu3.add(btnMatricula1);

        jMenuItem4.setText("Enviar Tarea");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem6.setText("Reporte Califiacion");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        btnSalir1.setText("Salir");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jMenu3.add(btnSalir1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMateriaActionPerformed

    private void btnIncio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncio1ActionPerformed
        new Menu(this.estudiante).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIncio1ActionPerformed

    private void btnMatricula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricula1ActionPerformed
        try {
            new EstudianteMatricula(this.estudiante).setVisible(true);
            this.dispose();
        } catch (EmptyException ex) {
            java.util.logging.Logger.getLogger(GuardarCiclo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMatricula1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        EntregaTarea et=new EntregaTarea(this.estudiante);
        this.dispose();
        et.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ReporteNotas rp=new ReporteNotas(this.estudiante);
        this.dispose();
        rp.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        new LoginPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnIncio1;
    private javax.swing.JMenuItem btnMatricula1;
    private javax.swing.JMenuItem btnSalir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private org.edisoncor.gui.panel.PanelImage pnlAzul;
    private org.edisoncor.gui.panel.PanelImage pnlGris;
    private javax.swing.JTable tblMostrarDatos;
    private javax.swing.JTable tblMostrarDatos1;
    public static javax.swing.JTextField txtDescripcion;
    public static javax.swing.JTextField txtMateria;
    public static javax.swing.JTextField txtNota;
    public static javax.swing.JTextField txtRetroaliemntacion;
    public static javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

}
