/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package matricula.vista;

import exeption.EmptyException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import lista.DynamicList;
import matricula.controlador.CarreraControl;
import matricula.controlador.CicloControl;
import matricula.controlador.MallaControl;
import matricula.modelo.Malla;
import matricula.vista.tabla.ModeloTablaCiclo;
import matricula.vista.tabla.ModeloTablaMalla;
import matricula.vista.util.UtilVistaCarrera;
import matricula.vista.util.UtilVistaMalla;
import usuarios.vista.Inicio;

/**
 *
 * @author darwi
 */
public class GuardarMalla extends javax.swing.JFrame {

    private ModeloTablaMalla mtc = new ModeloTablaMalla();
    private MallaControl mallaControl = new MallaControl();
    private CarreraControl carreraControl = new CarreraControl();
    private CicloControl cicloControl = new CicloControl();
    private ModeloTablaCiclo mtm = new ModeloTablaCiclo();

    public void cargarFacultades(DynamicList carreras) {
        mtc.setMallas(carreras);
        initComponents();
    }

    public Boolean verificar() {
        return (!txtNombre.getText().trim().isEmpty());
    }

    private void cargarTabla() {
        mtc.setMallas(mallaControl.getListMalla());
        tbCiclos.setModel(mtm);
        tbCiclos.updateUI();
        tbMalla.setModel(mtc);
        tbMalla.updateUI();
    }

    private void guardar() throws EmptyException {
        if (verificar()) {
            mallaControl.getMalla().setNombre(txtNombre.getText());
            mallaControl.getMalla().setId_Carrera(UtilVistaCarrera.obtenerCarrera(cbxCarrera).getId());
            mallaControl.getMalla().setFechaCreacion(JdFechaCreacion.getDate());

            if (mallaControl.persist()) {
                cargarTabla();
                limpiar();
                mallaControl.setMalla(null);
                
                DynamicList<Malla> mallas = carreraControl.getListCarrera().getInfo(cbxCarrera.getSelectedIndex()).getMallas();
                mallas.add(mallaControl.getListMalla().getInfo(mallaControl.getListMalla().getLength() - 1));
                carreraControl.getCarrera().setDescripcion(carreraControl.getListCarrera().getInfo(cbxCarrera.getSelectedIndex()).getDescripcion());
                carreraControl.getCarrera().setNombre(carreraControl.getListCarrera().getInfo(cbxCarrera.getSelectedIndex()).getNombre());
                carreraControl.getCarrera().setMallas(mallas);
                carreraControl.getCarrera().setId(carreraControl.getListCarrera().getInfo(cbxCarrera.getSelectedIndex()).getId());

                if (carreraControl.marge(carreraControl.getCarrera(), cbxCarrera.getSelectedIndex())) {
                    JOptionPane.showMessageDialog(null, "Datos guardados");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al agregar la malla a la carrera", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(null, "No se pudo guardar, hubo un error");
            }

        }

    }

    private void limpiar() {
        txtNombre.setText("");
        cargarTabla();
        mallaControl.setMalla(null);
    }

    public GuardarMalla() throws EmptyException {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarTabla();
        pnlAzul.setIcon(new ImageIcon("fotos/Azul.jpg"));
        pnlGris.setIcon(new ImageIcon("fotos/Gris.jpg"));
        UtilVistaCarrera.cargarcomboCarrera(cbxCarrera);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAzul = new org.edisoncor.gui.panel.PanelImage();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cbxCarrera = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JdFechaCreacion = new com.toedter.calendar.JDateChooser();
        btnVerCiclos = new javax.swing.JButton();
        btnAgregarCiclo = new javax.swing.JButton();
        pnlGris = new org.edisoncor.gui.panel.PanelImage();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMalla = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCiclos = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscar1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnAdmFacultad = new javax.swing.JMenuItem();
        btnAdmCarrera = new javax.swing.JMenuItem();
        btnAdmCiclo = new javax.swing.JMenuItem();
        btnAdmCursa = new javax.swing.JMenuItem();
        btnAdmMatricula = new javax.swing.JMenuItem();
        btnAdmPeriodo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAzul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("MALLA");
        pnlAzul.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Carrera:");
        pnlAzul.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        pnlAzul.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 239, -1));

        cbxCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlAzul.add(cbxCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 239, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlAzul.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre:");
        pnlAzul.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha:");
        pnlAzul.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        pnlAzul.add(JdFechaCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 240, -1));

        btnVerCiclos.setText("Ver Ciclos");
        btnVerCiclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCiclosActionPerformed(evt);
            }
        });
        pnlAzul.add(btnVerCiclos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, -1, -1));

        btnAgregarCiclo.setText("Argregar Ciclo");
        btnAgregarCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCicloActionPerformed(evt);
            }
        });
        pnlAzul.add(btnAgregarCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 120, -1));

        getContentPane().add(pnlAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 600));

        pnlGris.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        pnlGris.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 120, -1));

        tbMalla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbMalla);

        pnlGris.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 580, 101));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlGris.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 170, -1));

        jButton1.setText("Ordenar");
        pnlGris.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Texto:");
        pnlGris.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Criterio:");
        pnlGris.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 51));
        jLabel18.setText("MALLAS");
        pnlGris.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 51));
        jLabel19.setText("CICLOS");
        pnlGris.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        tbCiclos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbCiclos);

        pnlGris.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 580, 101));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Criterio:");
        pnlGris.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Texto:");
        pnlGris.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));
        pnlGris.add(txtBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 120, -1));

        jButton3.setText("Buscar");
        pnlGris.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jButton4.setText("Ordenar");
        pnlGris.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jButton5.setText("Buscar");
        pnlGris.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlGris.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 170, -1));

        getContentPane().add(pnlGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 640, 600));

        jMenu1.setText("Administración");

        btnAdmFacultad.setText("Facultad");
        btnAdmFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmFacultadActionPerformed(evt);
            }
        });
        jMenu1.add(btnAdmFacultad);

        btnAdmCarrera.setText("Carrera");
        btnAdmCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmCarreraActionPerformed(evt);
            }
        });
        jMenu1.add(btnAdmCarrera);

        btnAdmCiclo.setText("Ciclo");
        btnAdmCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmCicloActionPerformed(evt);
            }
        });
        jMenu1.add(btnAdmCiclo);

        btnAdmCursa.setText("Cursa");
        btnAdmCursa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmCursaActionPerformed(evt);
            }
        });
        jMenu1.add(btnAdmCursa);

        btnAdmMatricula.setText("Matricula");
        btnAdmMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmMatriculaActionPerformed(evt);
            }
        });
        jMenu1.add(btnAdmMatricula);

        btnAdmPeriodo.setText("Periodo Académico");
        btnAdmPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmPeriodoActionPerformed(evt);
            }
        });
        jMenu1.add(btnAdmPeriodo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdmFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmFacultadActionPerformed
        try {
            new GuardarFacultad().setVisible(true);
            this.dispose();
        } catch (EmptyException ex) {
            Logger.getLogger(GuardarFacultad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdmFacultadActionPerformed

    private void btnAdmCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmCarreraActionPerformed
        try {
            new GuardarCarrera().setVisible(true);
            this.dispose();
        } catch (EmptyException ex) {
            Logger.getLogger(GuardarFacultad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdmCarreraActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnAgregarCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCicloActionPerformed
        int filaSeleccionada = tbMalla.getSelectedRow();
        if (filaSeleccionada != -1) {
            try {
                new AgregarCiclo(filaSeleccionada).setVisible(true);
            } catch (Exception ex) {
                int i = JOptionPane.showConfirmDialog(null, "No hay ciclos para agregar \n ¿Desea crearlo?", "ADVERTENCIA", JOptionPane.OK_CANCEL_OPTION);
                if (i == JOptionPane.OK_OPTION) {
                    try {
                        new GuardarCiclo().setVisible(true);
                        this.dispose();
                    } catch (EmptyException ex1) {
                        JOptionPane.showConfirmDialog(null, "Hubo un problema al intentar crear el ciclo :c");
                    }
                }
            }
            cargarTabla();
        } else {
            JOptionPane.showConfirmDialog(null, "No ha seleccionado una malla de la tabla mallas", "ADVERTENCIA", JOptionPane.OK_CANCEL_OPTION);
        }
    }//GEN-LAST:event_btnAgregarCicloActionPerformed

    private void btnVerCiclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCiclosActionPerformed
        int filaSeleccionada = tbMalla.getSelectedRow();
        if (filaSeleccionada != -1) {
            try {
                if (mallaControl.getListMalla().getInfo(filaSeleccionada).getCiclos().getLength() == 0) {
                    JOptionPane.showConfirmDialog(null, "Esta facultad no tiene carreras", "ADVERTENCIA", JOptionPane.OK_CANCEL_OPTION);
                } else {
                    mtm.setCiclos(mallaControl.getListMalla().getInfo(filaSeleccionada).getCiclos());
                    tbCiclos.setModel(mtm);
                    tbCiclos.updateUI();
                }
            } catch (EmptyException ex) {
                Logger.getLogger(GuardarCiclo.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showConfirmDialog(null, "No ha seleccionado una malla de la tabla mallas", "ADVERTENCIA", JOptionPane.OK_CANCEL_OPTION);
        }
    }//GEN-LAST:event_btnVerCiclosActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            guardar();
        } catch (EmptyException ex) {
            Logger.getLogger(GuardarMalla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAdmCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmCicloActionPerformed
         try {
            new GuardarCiclo().setVisible(true);
            this.dispose();
        } catch (EmptyException ex) {
            Logger.getLogger(GuardarFacultad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdmCicloActionPerformed

    private void btnAdmCursaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmCursaActionPerformed
        new GuardarCursa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdmCursaActionPerformed

    private void btnAdmMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmMatriculaActionPerformed
        try {
            new GuardarMatricula().setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(GuardarMalla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdmMatriculaActionPerformed

    private void btnAdmPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmPeriodoActionPerformed
        new GuardarPeriodoAcademico().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdmPeriodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuardarMalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuardarMalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuardarMalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuardarMalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GuardarMalla().setVisible(true);
                } catch (EmptyException ex) {
                    Logger.getLogger(GuardarMalla.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JdFechaCreacion;
    private javax.swing.JMenuItem btnAdmCarrera;
    private javax.swing.JMenuItem btnAdmCiclo;
    private javax.swing.JMenuItem btnAdmCursa;
    private javax.swing.JMenuItem btnAdmFacultad;
    private javax.swing.JMenuItem btnAdmMatricula;
    private javax.swing.JMenuItem btnAdmPeriodo;
    private javax.swing.JButton btnAgregarCiclo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVerCiclos;
    private javax.swing.JComboBox<String> cbxCarrera;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.edisoncor.gui.panel.PanelImage pnlAzul;
    private org.edisoncor.gui.panel.PanelImage pnlGris;
    private javax.swing.JTable tbCiclos;
    private javax.swing.JTable tbMalla;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscar1;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
